### ISSUE TITLE
Random scroll

### ISSUE THREAD

**Issue by AndriusCTR** [Alverrt/ghost-scroll#3]
So how do I enable random, human like scroll (e.g. down)? Docs says nothing about that. If I provide number then it goes that much down and that's it. Where is human-like randomness?

**Comment by Alverrt** [comment]
Its imitating scroll behaviour on chrome session. Its randomness based on human scroll event in browser. Its not random random.

**Comment by AndriusCTR** [comment]
> Its imitating scroll behaviour on chrome session. Its randomness based on human scroll event in browser. Its not random random.

Don't even understand what that means...
